server:
  port: 10003

spring:
  application:
    name: vendor-server
  config:
    import: 'optional:configserver:'
  datasource:
    url: jdbc:postgresql://localhost:5454/vendor_db
    username: vendor
    password: 1234
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password: vendor

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    config:
      discovery:
        enabled: false
    openfeign:
      circuitbreaker:
        enabled: true


  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

resilience4j:
  retry:
    retry-aspect-order: 1
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - com.followMe.vendor_server.vendor.infrastructure.client.user.UserClientUnavailableException
          - com.followMe.vendor_server.vendor.infrastructure.client.hub.HubClientUnavailableException

    instances:
      user-server:
        baseConfig: default


  circuitbreaker:
    circuit-breaker-aspect-order: 2
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5 # 5개 요청 기반
        minimumNumberOfCalls: 3 #3개 임시
        failureRateThreshold: 50 # 50% 실패 시 Open
        waitDurationInOpenState: 10s # Open 후 Half-Open까지 대기 시간
        ignore-exceptions:
          - feign.FeignException.NotFound
          - feign.FeignException.BadRequest

    instances:
      user-server:
        baseConfig: default

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
logging:
  level:
    com.followMe.vendor_server: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    feign.Logger: DEBUG
